const lang = {
  en: {
    search: "Search",
    gptSearchPlaceHolder: "What would you like to watch today?",
    hi: "Hi ",
    signOut: "Sign out",
    topMovieSuggestions: "Top Movie Suggestions",
    homePage: "Home Page",
  },
  hi: {
    search: "खोज",
    gptSearchPlaceHolder: "आज आप क्या देखना चाहेंगे?",
    hi: "नमस्ते ",
    signOut: "साइन आउट",
    topMovieSuggestions: "शीर्ष फिल्म सुझाव",
    homePage: "मुख्य पृष्ठ",
  },
  es: {
    search: "Buscar",
    gptSearchPlaceHolder: "¿Qué te gustaría ver hoy?",
    hi: "Hola ",
    signOut: "Cerrar sesión",
    topMovieSuggestions: "Sugerencias de películas principales",
    homePage: "Página principal",
  },
  te: {
    search: "శోధన",
    gptSearchPlaceHolder: "ఈ రోజు మీరు ఏమి చూడాలనుకుంటున్నారు?",
    hi: "నమస్కారం ",
    signOut: "సైన్ అవుట్",
    topMovieSuggestions: "ప్రధాన చిత్రాల సూచనలు",
    homePage: "హోం పేజీ",
  },
  ta: {
    search: "தேடு",
    gptSearchPlaceHolder: "இன்று நீங்கள் என்ன காண விரும்புகிறீர்கள்?",
    hi: "வணக்கம் ",
    signOut: "வெளியேறு",
    topMovieSuggestions: "மேலான திரைப்படம் பரிந்துரைகள்",
    homePage: "முதன்மை பக்கம்",
  },
  fr: {
    search: "Rechercher",
    gptSearchPlaceHolder: "Que voudriez-vous regarder aujourd'hui?",
    hi: "Salut ",
    signOut: "Se déconnecter",
    topMovieSuggestions: "Meilleures suggestions de films",
    homePage: "Page d'accueil",
  },
  de: {
    search: "Suchen",
    gptSearchPlaceHolder: "Was möchten Sie heute sehen?",
    hi: "Hallo ",
    signOut: "Abmelden",
    topMovieSuggestions: "Top-Filmvorschläge",
    homePage: "Startseite",
  },
  zh: {
    search: "搜索",
    gptSearchPlaceHolder: "你今天想看什么？",
    hi: "你好 ",
    signOut: "登出",
    topMovieSuggestions: "热门电影推荐",
    homePage: "主页",
  },
  ja: {
    search: "検索",
    gptSearchPlaceHolder: "今日は何を見たいですか？",
    hi: "こんにちは ",
    signOut: "サインアウト",
    topMovieSuggestions: "トップ映画の提案",
    homePage: "ホームページ",
  },
  ko: {
    search: "검색",
    gptSearchPlaceHolder: "오늘 무엇을 보고 싶으신가요?",
    hi: "안녕하세요 ",
    signOut: "로그 아웃",
    topMovieSuggestions: "상위 영화 제안",
    homePage: "홈페이지",
  },
  pt: {
    search: "Pesquisar",
    gptSearchPlaceHolder: "O que você gostaria de assistir hoje?",
    hi: "Olá ",
    signOut: "Sair",
    topMovieSuggestions: "Principais sugestões de filmes",
    homePage: "Página inicial",
  },
  bn: {
    search: "অনুসন্ধান",
    gptSearchPlaceHolder: "আপনি আজ কী দেখতে চান?",
    hi: "হ্যালো ",
    signOut: "সাইন আউট",
    topMovieSuggestions: "শীর্ষ সিনেমার পরামর্শ",
    homePage: "হোম পৃষ্ঠা",
  },
  ar: {
    search: "بحث",
    gptSearchPlaceHolder: "ماذا تريد أن تشاهد اليوم؟",
    hi: "مرحبا ",
    signOut: "تسجيل الخروج",
    topMovieSuggestions: "أفضل اقتراحات الأفلام",
    homePage: "الصفحة الرئيسية",
  },
};

export default lang;
